/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.view;

import com.example.controller.MemberDAO;
import com.example.model.Member;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.imageio.stream.FileImageInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddMember extends javax.swing.JFrame {

    /**
     * Creates new form AddMember
     */
    private void clearFields() {
        path.setText("");
        m_address.setText("");
        m_mobile.setText("");
        m_email.setText("");

    }

    private boolean validData() {
        if (path.getText().equals("") || m_address.getText().equals("")
                || m_email.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please input in all fields");
            return false;
        } else {
            return true;
        }
    }

    public AddMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sidepane1 = new javax.swing.JPanel();
        sidepane2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sidepane3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sidepane4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sidepane5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sidepane6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        sidepane7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sidepane8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sidepane9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sidepane10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidepane11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        sidepane12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        sidepane13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        sidepane14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        addbook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        m_address = new javax.swing.JTextField();
        m_mobile = new javax.swing.JTextField();
        m_type = new javax.swing.JComboBox<>();
        m_email = new javax.swing.JTextField();
        m_male = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        J_female = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        b_save = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        userphoto = new javax.swing.JLabel();
        chooseimage = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        m_name = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(36, 47, 65));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\build\\classes\\Resources\\Admin.png")); // NOI18N
        sidepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("WELCOME TO CLMS");
        sidepane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("USER");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        sidepane1.setBackground(new java.awt.Color(102, 102, 0));
        sidepane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane2.setBackground(new java.awt.Color(36, 47, 65));
        sidepane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("USER");
        sidepane2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane1.add(sidepane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("SEARCH BOOK");
        sidepane1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane.add(sidepane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        sidepane3.setBackground(new java.awt.Color(0, 51, 51));
        sidepane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("SEARCH MEMBER");
        sidepane3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane4.setBackground(new java.awt.Color(36, 47, 65));
        sidepane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("USER");
        sidepane4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane3.add(sidepane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        sidepane5.setBackground(new java.awt.Color(102, 102, 0));
        sidepane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("ISSUE BOOK");
        sidepane5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane6.setBackground(new java.awt.Color(36, 47, 65));
        sidepane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("USER");
        sidepane6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane5.add(sidepane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        sidepane7.setBackground(new java.awt.Color(0, 51, 51));
        sidepane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("RETURN BOOK");
        sidepane7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane8.setBackground(new java.awt.Color(36, 47, 65));
        sidepane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("USER");
        sidepane8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane7.add(sidepane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        sidepane9.setBackground(new java.awt.Color(102, 102, 0));
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("RENEW BOOK");
        sidepane9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane10.setBackground(new java.awt.Color(36, 47, 65));
        sidepane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("USER");
        sidepane10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane9.add(sidepane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 40));

        sidepane11.setBackground(new java.awt.Color(0, 51, 51));
        sidepane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setText("ADD BOOK");
        sidepane11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane12.setBackground(new java.awt.Color(36, 47, 65));
        sidepane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("USER");
        sidepane12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane11.add(sidepane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        sidepane13.setBackground(new java.awt.Color(96, 212, 196));
        sidepane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("ADD MEMBER");
        sidepane13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane14.setBackground(new java.awt.Color(36, 47, 65));
        sidepane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("USER");
        sidepane14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane13.add(sidepane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        jPanel1.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 520));

        addbook.setBackground(new java.awt.Color(96, 212, 196));
        addbook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("MEMBERSHIP :");
        addbook.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setLabelFor(m_address);
        jLabel2.setText("NAME :");
        addbook.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("MOBILE NO.:");
        addbook.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("EMAIL :");
        addbook.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        m_address.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_addressActionPerformed(evt);
            }
        });
        addbook.add(m_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 250, 30));

        m_mobile.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_mobileActionPerformed(evt);
            }
        });
        m_mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                m_mobileKeyTyped(evt);
            }
        });
        addbook.add(m_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 30));

        m_type.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Lifetime" }));
        m_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_typeActionPerformed(evt);
            }
        });
        addbook.add(m_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, 30));

        m_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_emailActionPerformed(evt);
            }
        });
        addbook.add(m_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 30));

        m_male.setBackground(new java.awt.Color(96, 212, 196));
        buttonGroup1.add(m_male);
        m_male.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_male.setText("Male");
        m_male.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                m_maleItemStateChanged(evt);
            }
        });
        addbook.add(m_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setLabelFor(m_address);
        jLabel9.setText("ADDRESS : ");
        addbook.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        J_female.setBackground(new java.awt.Color(96, 212, 196));
        buttonGroup1.add(J_female);
        J_female.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        J_female.setText("Female");
        J_female.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                J_femaleItemStateChanged(evt);
            }
        });
        addbook.add(J_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setText("GENDER :");
        addbook.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        b_save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        b_save.setText("SAVE");
        b_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saveActionPerformed(evt);
            }
        });
        addbook.add(b_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addbook.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        userphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Library1.jpg"))); // NOI18N
        addbook.add(userphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 110, 120));

        chooseimage.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chooseimage.setText("Choose  Photo...");
        chooseimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseimageActionPerformed(evt);
            }
        });
        addbook.add(chooseimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        path.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });
        addbook.add(path, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 250, 30));

        m_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        m_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_nameActionPerformed(evt);
            }
        });
        addbook.add(m_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 290, 30));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\src\\Resources\\back.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        addbook.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 40));

        labelSearch.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelSearch.setText("Add Member");
        addbook.add(labelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jPanel1.add(addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 730, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_addressActionPerformed

    private void m_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_mobileActionPerformed

    private void m_mobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_m_mobileKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_m_mobileKeyTyped

    private void m_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_typeActionPerformed

    private void m_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_emailActionPerformed

    private void chooseimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseimageActionPerformed

        JFileChooser chooser = new JFileChooser();

        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
//        String filename=f.getAbsolutePath();
//        File destination = new File("/Resources/memberimage/" + f.getName());
//        boolean success = f.renameTo(destination);

        String filename = f.getAbsolutePath();
        path.setText(filename);
        
        ImageIcon icon=new ImageIcon(filename);
        Image img=icon.getImage();
        Image img1=(Image)img.getScaledInstance(userphoto.getWidth(), userphoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon1=new ImageIcon(img1);
        userphoto.setIcon(icon1);
        
        
        
      //  userphoto.setIcon(icon);
//       try{
//        File image=new File(filename);
//           FileInputStream fis=new FileInputStream(image);
//           ByteArrayOutputStream bos=new ByteArrayOutputStream();
//           byte[] buf=new byte[1024];
//           for(int readNum;(readNum=fis.read(buf))!=-1;){
//               bos.write(buf,0,readNum);
//           
//       }
//          // person_image=bos.toByteArray();
//          
//    }catch(Exception e){
//               System.out.println(e);
//               }
        /* try {
            FileOutputStream fout = new FileOutputStream("/Resources/memberimage/");
            //String str = sajiloeditor.SajiloEditor.t1.getText();
            byte b[] = str.getBytes();
            fout.write(b);
        } catch (Exception ex) {
            System.out.println("ex");
        }
      String in="/Resources/memberimage/net ho.JPG";
      ImageIcon image = new ImageIcon(
                        getClass().getResource(in));
                           String msg="Image not found"; 
            if (image != null) {
                userphoto.setIcon(image);
                userphoto.setText("");
            } else {
                userphoto.setText(msg);
            }
          
    }//GEN-LAST:event_chooseimageActionPerformed

    */
    }
    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void b_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saveActionPerformed
        // TODO add your handling code here:

        if (validData()) {
            String member_name = m_name.getText();

            String member_address = m_address.getText();

            // Should be replace with radio   String book_auther=m_email.getText();
            long member_mobile = Long.parseLong(m_mobile.getText());
            String member_email = m_email.getText();
            String Fileimg = path.getText();

            String membership_type = m_type.getSelectedItem().toString();
            //check the fields
            // if(validData()){
            //create object of model class book and set these value
            Member ob = new Member();
            ob.setName(member_name);
            ob.setAddress(member_address);
            ob.setGender("Male");
            ob.setMobile(member_mobile);
            ob.setEmail(member_email);
            ob.setMembership(membership_type);
            ob.setImg(Fileimg);

            MemberDAO bDAO = new MemberDAO();
            bDAO.insertData(ob);
            JOptionPane.showMessageDialog(null, "Member Recorded Sucessfully", "infobox", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        }
        // }

    }//GEN-LAST:event_b_saveActionPerformed

    private void J_femaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_J_femaleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_J_femaleItemStateChanged

    private void m_maleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_m_maleItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_m_maleItemStateChanged

    private void m_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_nameActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new SearchBook().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton J_female;
    private javax.swing.JPanel addbook;
    private javax.swing.JButton b_save;
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton chooseimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JTextField m_address;
    private javax.swing.JTextField m_email;
    private javax.swing.JRadioButton m_male;
    private javax.swing.JTextField m_mobile;
    private javax.swing.JTextField m_name;
    private javax.swing.JComboBox<String> m_type;
    private javax.swing.JTextField path;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel sidepane1;
    private javax.swing.JPanel sidepane10;
    private javax.swing.JPanel sidepane11;
    private javax.swing.JPanel sidepane12;
    private javax.swing.JPanel sidepane13;
    private javax.swing.JPanel sidepane14;
    private javax.swing.JPanel sidepane2;
    private javax.swing.JPanel sidepane3;
    private javax.swing.JPanel sidepane4;
    private javax.swing.JPanel sidepane5;
    private javax.swing.JPanel sidepane6;
    private javax.swing.JPanel sidepane7;
    private javax.swing.JPanel sidepane8;
    private javax.swing.JPanel sidepane9;
    private javax.swing.JLabel userphoto;
    // End of variables declaration//GEN-END:variables
private ImageIcon format = null;
//String filename=null;
    int s = 0;
//byte[] person_image=null;
}
