/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.view;

import com.example.common.DBConnection;
import com.example.controller.IssueDAO;
import com.example.model.Book;
import com.example.model.Issue;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    private boolean validData() {
        if (text_mid.getText().equals("") || text_bid.getText().equals("")
                || text_isbn.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select Member and Book");
            return false;
        } else {
            return true;
        }
    }

    public void loadmembersFields(String data) {

        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from member where id=" + data + "";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                int id = rs.getInt("id");
                String id1 = id + "";
                String name = rs.getString("name");
                String email = rs.getString("email");
                long mobile = rs.getLong("mobile");
                String photo =rs.getString("img");
                ImageIcon icon=new ImageIcon(photo);
         Image img=icon.getImage();
        Image img1=(Image)img.getScaledInstance(userphoto.getWidth(), userphoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icon1=new ImageIcon(img1);
        userphoto.setIcon(icon1);
                //text_mid.setText(id1); 
                text_name.setText(name);
                text_email.setText(email);
                text_mobile.setText(mobile + "");
                //userphoto.setIcon(photo);

            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }

    public void loadbooksFields(String data) {

        try {
            Connection con = DBConnection.getConnection();
            String sql = "select * from book where id=" + data + "";

            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                int id = rs.getInt("id");
                String id1 = id + "";
                String name = rs.getString("name");

                long isbn = rs.getLong("isbn");
                String auther = rs.getString("auther");

                //text_bid.setText(id1); 
                text_bname.setText(name);
                text_bauther.setText(auther);
                text_isbn.setText(isbn + "");

            }

        } catch (Exception e) {
            System.out.println(e);

        }
    }
     public void loadTableData(String data){
        
    
       
        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from issue where mid="+data+"";
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            table_issue.setModel(DbUtils.resultSetToTableModel(rs));
           
                
            
        }catch(Exception e){
            System.out.println(e);
            
        }
     }
     private void clearBookDetails(){
         text_bid.setText("");
         text_bname.setText("");
                text_bauther.setText("");
                text_isbn.setText("");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        text_mid = new javax.swing.JTextField();
        search_book = new javax.swing.JButton();
        text_name = new javax.swing.JTextField();
        text_email = new javax.swing.JTextField();
        text_mobile = new javax.swing.JTextField();
        lmembername = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_bid = new javax.swing.JTextField();
        search_member = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        text_bname = new javax.swing.JTextField();
        text_isbn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_issue = new javax.swing.JTable();
        btn_issue = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        userphoto = new javax.swing.JLabel();
        text_bauther = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        labelSearch = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sidepane1 = new javax.swing.JPanel();
        sidepane2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        sidepane3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sidepane4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sidepane5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sidepane6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        sidepane7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sidepane8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sidepane9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sidepane10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidepane11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        sidepane12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        sidepane13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        sidepane14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(96, 212, 196));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_mid.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_midActionPerformed(evt);
            }
        });
        jPanel1.add(text_mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 81, 30));

        search_book.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search_book.setText("SEARCH");
        search_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_bookActionPerformed(evt);
            }
        });
        jPanel1.add(search_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        text_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nameActionPerformed(evt);
            }
        });
        jPanel1.add(text_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 177, 30));

        text_email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_emailActionPerformed(evt);
            }
        });
        jPanel1.add(text_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 211, 30));

        text_mobile.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_mobileActionPerformed(evt);
            }
        });
        jPanel1.add(text_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 129, 30));

        lmembername.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jPanel1.add(lmembername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("MOBILE :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("EMAIL :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("MID :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        text_bid.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_bidActionPerformed(evt);
            }
        });
        jPanel1.add(text_bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 70, 30));

        search_member.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search_member.setText("SEARCH");
        search_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_memberActionPerformed(evt);
            }
        });
        jPanel1.add(search_member, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setText("BID");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setText("NAME");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setText("AUTHER : ");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        text_bname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_bnameActionPerformed(evt);
            }
        });
        jPanel1.add(text_bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 200, 30));

        text_isbn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_isbnActionPerformed(evt);
            }
        });
        jPanel1.add(text_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 129, 30));

        jScrollPane1.setViewportView(table_issue);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 631, 211));

        btn_issue.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_issue.setText("ISSUE");
        btn_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_issueActionPerformed(evt);
            }
        });
        jPanel1.add(btn_issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel28.setText("ISBN");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        userphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Library1.jpg"))); // NOI18N
        jPanel1.add(userphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, 130));

        text_bauther.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        text_bauther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_bautherActionPerformed(evt);
            }
        });
        jPanel1.add(text_bauther, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 200, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setText("NAME :");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel29.setText("NAME :");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\src\\Resources\\back.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 40));

        labelSearch.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelSearch.setText("Issue Book");
        jPanel1.add(labelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 740, 510));

        sidepane.setBackground(new java.awt.Color(36, 47, 65));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\build\\classes\\Resources\\Admin.png")); // NOI18N
        sidepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("WELCOME TO CLMS");
        sidepane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("USER");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        sidepane1.setBackground(new java.awt.Color(102, 102, 0));
        sidepane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane2.setBackground(new java.awt.Color(36, 47, 65));
        sidepane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("USER");
        sidepane2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane1.add(sidepane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("SEARCH BOOK");
        sidepane1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane.add(sidepane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        sidepane3.setBackground(new java.awt.Color(0, 51, 51));
        sidepane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("SEARCH MEMBER");
        sidepane3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane4.setBackground(new java.awt.Color(36, 47, 65));
        sidepane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("USER");
        sidepane4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane3.add(sidepane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        sidepane5.setBackground(new java.awt.Color(96, 212, 196));
        sidepane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("ISSUE BOOK");
        sidepane5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane6.setBackground(new java.awt.Color(36, 47, 65));
        sidepane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("USER");
        sidepane6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane5.add(sidepane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        sidepane7.setBackground(new java.awt.Color(0, 51, 51));
        sidepane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("RETURN BOOK");
        sidepane7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane8.setBackground(new java.awt.Color(36, 47, 65));
        sidepane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("USER");
        sidepane8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane7.add(sidepane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        sidepane9.setBackground(new java.awt.Color(102, 102, 0));
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("RENEW BOOK");
        sidepane9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane10.setBackground(new java.awt.Color(36, 47, 65));
        sidepane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("USER");
        sidepane10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane9.add(sidepane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 40));

        sidepane11.setBackground(new java.awt.Color(0, 51, 51));
        sidepane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setText("ADD BOOK");
        sidepane11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane12.setBackground(new java.awt.Color(36, 47, 65));
        sidepane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("USER");
        sidepane12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane11.add(sidepane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        sidepane13.setBackground(new java.awt.Color(102, 102, 0));
        sidepane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("ADD MEMBER");
        sidepane13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane14.setBackground(new java.awt.Color(36, 47, 65));
        sidepane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("USER");
        sidepane14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane13.add(sidepane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        getContentPane().add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_midActionPerformed

    private void text_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nameActionPerformed

    private void text_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_emailActionPerformed

    private void text_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_mobileActionPerformed

    private void text_bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_bidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_bidActionPerformed

    private void text_bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_bnameActionPerformed

    private void text_isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_isbnActionPerformed

    private void search_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_memberActionPerformed

        String data = text_mid.getText();
        //String type=combo_type.getSelectedItem().toString();
        loadmembersFields(data);
        loadTableData(data);
        lmembername.setText(text_name.getText());


    }//GEN-LAST:event_search_memberActionPerformed

    private void search_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_bookActionPerformed
        // TODO add your handling code here:

        String data = text_bid.getText();
        //String type=combo_book.getSelectedItem().toString();
        loadbooksFields(data);
    }//GEN-LAST:event_search_bookActionPerformed

    private void btn_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_issueActionPerformed
        // TODO add your handling code here:
        if (validData()) {
            
            //JDialog dialog=new JDialog();
            

            int m_id = Integer.parseInt(text_mid.getText());
            int b_id = Integer.parseInt(text_bid.getText());
           
            //SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
           
          // Date issuedate = new Date();
            //dateFormat.format(issuedate);
            boolean status=false;
            

            Issue ob = new Issue();
            ob.setMid(m_id);
            ob.setBid(b_id);
            ob.setStatus(status);
            

           // ob.setIssuedate(issuedate);
           // java.util.Date returndate = new Date(rs.getDate("return").getTime());
           // ob.setReturndate(returndate);

           

            IssueDAO idao = new IssueDAO();
            idao.insertData(ob);
            clearBookDetails();

        }


    }//GEN-LAST:event_btn_issueActionPerformed

    private void text_bautherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_bautherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_bautherActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new SearchBook().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btn_issue;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JLabel lmembername;
    private javax.swing.JPanel parent;
    private javax.swing.JButton search_book;
    private javax.swing.JButton search_member;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel sidepane1;
    private javax.swing.JPanel sidepane10;
    private javax.swing.JPanel sidepane11;
    private javax.swing.JPanel sidepane12;
    private javax.swing.JPanel sidepane13;
    private javax.swing.JPanel sidepane14;
    private javax.swing.JPanel sidepane2;
    private javax.swing.JPanel sidepane3;
    private javax.swing.JPanel sidepane4;
    private javax.swing.JPanel sidepane5;
    private javax.swing.JPanel sidepane6;
    private javax.swing.JPanel sidepane7;
    private javax.swing.JPanel sidepane8;
    private javax.swing.JPanel sidepane9;
    private javax.swing.JTable table_issue;
    private javax.swing.JTextField text_bauther;
    private javax.swing.JTextField text_bid;
    private javax.swing.JTextField text_bname;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_isbn;
    private javax.swing.JTextField text_mid;
    private javax.swing.JTextField text_mobile;
    private javax.swing.JTextField text_name;
    private javax.swing.JLabel userphoto;
    // End of variables declaration//GEN-END:variables

}
