/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.view;

/**
 *
 * @author Admin
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        sidepane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sidepane1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidepane2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        sidepane3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sidepane4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sidepane5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sidepane6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sidepane7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sidepane8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sidepane9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        sidepane10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sidepane11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sidepane12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sidepane13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidepane14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(36, 47, 65));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\build\\classes\\Resources\\Admin.png")); // NOI18N
        sidepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("WELCOME TO CLMS");
        sidepane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("USER");
        sidepane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        sidepane1.setBackground(new java.awt.Color(96, 212, 196));
        sidepane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("SEARCH BOOK");
        jLabel3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel3MouseWheelMoved(evt);
            }
        });
        sidepane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane2.setBackground(new java.awt.Color(36, 47, 65));
        sidepane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("USER");
        sidepane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane1.add(sidepane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        sidepane3.setBackground(new java.awt.Color(0, 51, 51));
        sidepane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("SEARCH MEMBER");
        sidepane3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane4.setBackground(new java.awt.Color(36, 47, 65));
        sidepane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("USER");
        sidepane4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane3.add(sidepane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        sidepane5.setBackground(new java.awt.Color(102, 102, 0));
        sidepane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("ISSUE BOOK");
        sidepane5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane6.setBackground(new java.awt.Color(36, 47, 65));
        sidepane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("USER");
        sidepane6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane5.add(sidepane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        sidepane7.setBackground(new java.awt.Color(0, 51, 51));
        sidepane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("RETURN BOOK");
        sidepane7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane8.setBackground(new java.awt.Color(36, 47, 65));
        sidepane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("USER");
        sidepane8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane7.add(sidepane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        sidepane9.setBackground(new java.awt.Color(102, 102, 0));
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("RENEW BOOK");
        sidepane9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane10.setBackground(new java.awt.Color(36, 47, 65));
        sidepane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("USER");
        sidepane10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane9.add(sidepane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 40));

        sidepane11.setBackground(new java.awt.Color(0, 51, 51));
        sidepane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("ADD BOOK");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        sidepane11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane12.setBackground(new java.awt.Color(36, 47, 65));
        sidepane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("USER");
        sidepane12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane11.add(sidepane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        sidepane13.setBackground(new java.awt.Color(102, 102, 0));
        sidepane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("ADD MEMBER");
        sidepane13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane14.setBackground(new java.awt.Color(36, 47, 65));
        sidepane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("USER");
        sidepane14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane13.add(sidepane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        jDesktopPane1.setLayer(sidepane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 720, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel3MouseWheelMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel3MouseWheelMoved

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        new AddBook().setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel sidepane1;
    private javax.swing.JPanel sidepane10;
    private javax.swing.JPanel sidepane11;
    private javax.swing.JPanel sidepane12;
    private javax.swing.JPanel sidepane13;
    private javax.swing.JPanel sidepane14;
    private javax.swing.JPanel sidepane2;
    private javax.swing.JPanel sidepane3;
    private javax.swing.JPanel sidepane4;
    private javax.swing.JPanel sidepane5;
    private javax.swing.JPanel sidepane6;
    private javax.swing.JPanel sidepane7;
    private javax.swing.JPanel sidepane8;
    private javax.swing.JPanel sidepane9;
    // End of variables declaration//GEN-END:variables
}
