/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.view;

import com.example.common.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class SearchMember extends javax.swing.JFrame {

    /**
     * Creates new form SearchMember
     */
    public SearchMember() {
        initComponents();
    }
    
     private void loadTableData(String type,String data){
        
    
       
        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from member where "+type+" like '"+data+"%'";
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            table_member.setModel(DbUtils.resultSetToTableModel(rs));
           
                
            
        }catch(Exception e){
            System.out.println(e);
            
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_searchtype = new javax.swing.JComboBox<>();
        searchbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_member = new javax.swing.JTable();
        back = new javax.swing.JLabel();
        sidepane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sidepane1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidepane2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        sidepane3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sidepane4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sidepane5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sidepane6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sidepane7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sidepane8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sidepane9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        sidepane10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sidepane11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sidepane12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sidepane13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidepane14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(96, 212, 196));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Search Member");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("SEARCH BY :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        combo_searchtype.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        combo_searchtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Name", "Address", "Mobile" }));
        combo_searchtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_searchtypeItemStateChanged(evt);
            }
        });
        combo_searchtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_searchtypeActionPerformed(evt);
            }
        });
        jPanel1.add(combo_searchtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        searchbox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 350, 30));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jScrollPane1.setViewportView(table_member);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 650, 310));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\src\\Resources\\back.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 40));

        parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 740, 510));

        sidepane.setBackground(new java.awt.Color(36, 47, 65));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("WELCOME TO CLMS");
        sidepane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("USER");
        sidepane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        sidepane1.setBackground(new java.awt.Color(102, 102, 0));
        sidepane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("SEARCH BOOK");
        sidepane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane2.setBackground(new java.awt.Color(36, 47, 65));
        sidepane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("USER");
        sidepane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane1.add(sidepane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        sidepane3.setBackground(new java.awt.Color(96, 212, 196));
        sidepane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("SEARCH MEMBER");
        sidepane3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane4.setBackground(new java.awt.Color(36, 47, 65));
        sidepane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("USER");
        sidepane4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane3.add(sidepane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        sidepane5.setBackground(new java.awt.Color(102, 102, 0));
        sidepane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane5MouseClicked(evt);
            }
        });
        sidepane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("ISSUE BOOK");
        sidepane5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane6.setBackground(new java.awt.Color(36, 47, 65));
        sidepane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("USER");
        sidepane6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane5.add(sidepane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        sidepane7.setBackground(new java.awt.Color(0, 51, 51));
        sidepane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("RETURN BOOK");
        sidepane7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane8.setBackground(new java.awt.Color(36, 47, 65));
        sidepane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("USER");
        sidepane8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane7.add(sidepane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        sidepane9.setBackground(new java.awt.Color(102, 102, 0));
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("RENEW BOOK");
        sidepane9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane10.setBackground(new java.awt.Color(36, 47, 65));
        sidepane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("USER");
        sidepane10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane9.add(sidepane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 40));

        sidepane11.setBackground(new java.awt.Color(0, 51, 51));
        sidepane11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane11MouseClicked(evt);
            }
        });
        sidepane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("ADD BOOK");
        sidepane11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane12.setBackground(new java.awt.Color(36, 47, 65));
        sidepane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("USER");
        sidepane12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane11.add(sidepane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        sidepane13.setBackground(new java.awt.Color(102, 102, 0));
        sidepane13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane13MouseClicked(evt);
            }
        });
        sidepane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("ADD MEMBER");
        sidepane13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane14.setBackground(new java.awt.Color(36, 47, 65));
        sidepane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("USER");
        sidepane14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane13.add(sidepane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\build\\classes\\Resources\\Admin.png")); // NOI18N
        sidepane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        parent.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 250, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void combo_searchtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_searchtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_searchtypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        String data=searchbox.getText();
        
        String Searchby= combo_searchtype.getSelectedItem().toString();
        loadTableData(Searchby,data);
        
    }//GEN-LAST:event_searchboxKeyPressed

    private void combo_searchtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_searchtypeItemStateChanged
        // TODO add your handling code here:
        //String Searchby= combo_searchtype.getSelectedItem().toString();
    }//GEN-LAST:event_combo_searchtypeItemStateChanged

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
 new SearchBook().setVisible(true);
        setVisible(false);        
    }//GEN-LAST:event_backMouseClicked

    private void sidepane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane5MouseClicked
         new IssueBook().setVisible(true);
        setVisible(false);  
    }//GEN-LAST:event_sidepane5MouseClicked

    private void sidepane11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane11MouseClicked
        new AddBook().setVisible(true);
        setVisible(false);  
    }//GEN-LAST:event_sidepane11MouseClicked

    private void sidepane13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane13MouseClicked
        // TODO add your handling code here:
         new AddMember().setVisible(true);
        setVisible(false);  
    }//GEN-LAST:event_sidepane13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JComboBox<String> combo_searchtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel parent;
    private javax.swing.JTextField searchbox;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel sidepane1;
    private javax.swing.JPanel sidepane10;
    private javax.swing.JPanel sidepane11;
    private javax.swing.JPanel sidepane12;
    private javax.swing.JPanel sidepane13;
    private javax.swing.JPanel sidepane14;
    private javax.swing.JPanel sidepane2;
    private javax.swing.JPanel sidepane3;
    private javax.swing.JPanel sidepane4;
    private javax.swing.JPanel sidepane5;
    private javax.swing.JPanel sidepane6;
    private javax.swing.JPanel sidepane7;
    private javax.swing.JPanel sidepane8;
    private javax.swing.JPanel sidepane9;
    private javax.swing.JTable table_member;
    // End of variables declaration//GEN-END:variables
}
