/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.example.view;
import java.util.Calendar;
import java.util.GregorianCalendar;
import com.example.common.DBConnection;
import com.example.controller.BookDAO;
import com.example.model.Book;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
 import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class SearchBook extends javax.swing.JFrame {
    public SearchBook() {
      initComponents();
    }

    /**
     * Creates new form SearchBook
     */
     DefaultTableModel model;
    /* private void cleartableRows(){
    int count=jTable_book.getRowCount();
    for(int i=0;i<count;i++){
        model.removeRow(0);
    }
     }
    */
     private void loadTableData(String type,String data){
        
    
       
        try{
            Connection con=DBConnection.getConnection();
            String sql="select * from book where "+type+" like '"+data+"%'";
            
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            jTable_book.setModel(DbUtils.resultSetToTableModel(rs));
           
                
            
        }catch(Exception e){
            System.out.println(e);
            
        }
        
        
        
        
         
                
       
       //.. model=new DefaultTableModel(null,new String[]{"Id","Name","ISBN","Auther","Publication","Price","Category"});
       // jTable_book.setModel(model);
        
    //cleartableRows();
        BookDAO bDAO=new BookDAO();
       /* ArrayList<Book> list=bDAO.fetchData();
        for(int i=0;i<list.size();i++){
            model.addRow(new Object[]{list.get(i).getId(),
            list.get(i).getName(), list.get(i).getIsbn(),
             list.get(i).getAuther(), list.get(i).getPublication(),
            list.get(i).getPrice(),list.get(i).getCategory()});
            
        }}*/
//   // 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sidepane1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sidepane2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        sidepane3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        sidepane4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sidepane5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sidepane6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sidepane7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sidepane8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        sidepane9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        sidepane10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        sidepane11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        sidepane12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        sidepane13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidepane14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo_book_type = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_book = new javax.swing.JTable();
        labelSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(96, 212, 196));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(36, 47, 65));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dinesh\\Documents\\NetBeansProjects\\clms\\build\\classes\\Resources\\Admin.png")); // NOI18N
        sidepane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 80));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("WELCOME TO CLMS");
        sidepane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("USER");
        sidepane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        sidepane1.setBackground(new java.awt.Color(96, 212, 196));
        sidepane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("SEARCH BOOK");
        jLabel3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel3MouseWheelMoved(evt);
            }
        });
        sidepane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane2.setBackground(new java.awt.Color(36, 47, 65));
        sidepane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("USER");
        sidepane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane1.add(sidepane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 40));

        sidepane3.setBackground(new java.awt.Color(0, 51, 51));
        sidepane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane3MouseClicked(evt);
            }
        });
        sidepane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("SEARCH MEMBER");
        sidepane3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane4.setBackground(new java.awt.Color(36, 47, 65));
        sidepane4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("USER");
        sidepane4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane3.add(sidepane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        sidepane5.setBackground(new java.awt.Color(102, 102, 0));
        sidepane5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane5MouseClicked(evt);
            }
        });
        sidepane5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("ISSUE BOOK");
        sidepane5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane6.setBackground(new java.awt.Color(36, 47, 65));
        sidepane6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("USER");
        sidepane6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane5.add(sidepane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        sidepane7.setBackground(new java.awt.Color(0, 51, 51));
        sidepane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane7MouseClicked(evt);
            }
        });
        sidepane7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("RETURN BOOK");
        sidepane7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane8.setBackground(new java.awt.Color(36, 47, 65));
        sidepane8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("USER");
        sidepane8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane7.add(sidepane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        sidepane9.setBackground(new java.awt.Color(102, 102, 0));
        sidepane9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane9MouseClicked(evt);
            }
        });
        sidepane9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("RENEW BOOK");
        sidepane9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane10.setBackground(new java.awt.Color(36, 47, 65));
        sidepane10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("USER");
        sidepane10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane9.add(sidepane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, 40));

        sidepane11.setBackground(new java.awt.Color(0, 51, 51));
        sidepane11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane11MouseClicked(evt);
            }
        });
        sidepane11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("ADD BOOK");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        sidepane11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane12.setBackground(new java.awt.Color(36, 47, 65));
        sidepane12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("USER");
        sidepane12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane11.add(sidepane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 40));

        sidepane13.setBackground(new java.awt.Color(102, 102, 0));
        sidepane13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sidepane13MouseClicked(evt);
            }
        });
        sidepane13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("ADD MEMBER");
        sidepane13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane14.setBackground(new java.awt.Color(36, 47, 65));
        sidepane14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("USER");
        sidepane14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 40));

        sidepane13.add(sidepane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, 40));

        sidepane.add(sidepane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 40));

        parent.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 510));

        jPanel1.setBackground(new java.awt.Color(96, 212, 196));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("SEARCH BY :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        combo_book_type.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        combo_book_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Name", "ISBN", "Auther", "Publication" }));
        combo_book_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_book_typeItemStateChanged(evt);
            }
        });
        combo_book_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_book_typeActionPerformed(evt);
            }
        });
        jPanel1.add(combo_book_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        btn_search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        searchbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchboxKeyTyped(evt);
            }
        });
        jPanel1.add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 340, 30));

        jTable_book.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable_book.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable_book);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 670, 310));

        labelSearch.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        labelSearch.setText("Search Book");
        jPanel1.add(labelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        parent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 740, 510));

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_book_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_book_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_book_typeActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        new AddBook().setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel3MouseWheelMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel3MouseWheelMoved

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
      //  String searchdata=searchbox.getText();
        
       // loadTableData(searchdata);
       
    }//GEN-LAST:event_btn_searchActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
       
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_searchboxKeyPressed

    private void combo_book_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_book_typeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_book_typeItemStateChanged

    private void sidepane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane3MouseClicked
        // TODO add your handling code here:
        new SearchMember().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sidepane3MouseClicked

    private void sidepane11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane11MouseClicked
        // TODO add your handling code here:
        new AddBook().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_sidepane11MouseClicked

    private void sidepane13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane13MouseClicked
new AddMember().setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_sidepane13MouseClicked

    private void searchboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyTyped
        // TODO add your handling code here:
         String data=searchbox.getText();
        String searchby=combo_book_type.getSelectedItem().toString();
        loadTableData(searchby,data);
    }//GEN-LAST:event_searchboxKeyTyped

    private void sidepane5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane5MouseClicked
        // TODO add your handling code here:
         new IssueBook().setVisible(true);
        setVisible(false);  
    }//GEN-LAST:event_sidepane5MouseClicked

    private void sidepane7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane7MouseClicked
        // TODO add your handling code here:
        new ReturnBook().setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_sidepane7MouseClicked

    private void sidepane9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepane9MouseClicked
        // TODO add your handling code here:
        new RenewBook().setVisible(true);
        setVisible(false); 
    }//GEN-LAST:event_sidepane9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> combo_book_type;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_book;
    private javax.swing.JLabel labelSearch;
    private javax.swing.JPanel parent;
    private javax.swing.JTextField searchbox;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel sidepane1;
    private javax.swing.JPanel sidepane10;
    private javax.swing.JPanel sidepane11;
    private javax.swing.JPanel sidepane12;
    private javax.swing.JPanel sidepane13;
    private javax.swing.JPanel sidepane14;
    private javax.swing.JPanel sidepane2;
    private javax.swing.JPanel sidepane3;
    private javax.swing.JPanel sidepane4;
    private javax.swing.JPanel sidepane5;
    private javax.swing.JPanel sidepane6;
    private javax.swing.JPanel sidepane7;
    private javax.swing.JPanel sidepane8;
    private javax.swing.JPanel sidepane9;
    // End of variables declaration//GEN-END:variables
}
